version: 2.1
workflows:
  build-deploy:
    jobs:
      - deployment
machine:
  java:
    version: oraclejdk8

jobs:
  deployment:
    machine: true
    steps:
      -checkout
    run:
      staging:
        branch: master
        heroku:
          appname: circle-ci-tes